### ISSUE TITLE
Full script broke if there is an error in .json files

### ISSUE THREAD

**Issue by b1zzu** [karlisup/component-library-core#2]
Json parser raise a SyntaxError that makes broke the full script.
The error should be displayed but the execution must continue normally.

**Comment by karlisup** [comment]
Thank you for reporting the bug @davbizz. Could you upload screenshot or paste some more details about the SyntaxError, please?

**Comment by b1zzu** [comment]
This is the full console output

```
[11:54:34] Working directory changed to c:\Users\pb00230\Erizone\si-design\_front-end
[11:54:35] Using gulpfile c:\Users\pb00230\Erizone\si-design\_front-end\gulpfile.js
[11:54:35] Starting 'default'...
[11:54:35] Starting 'watch'...
[11:54:35] Starting 'styleguide'...
[11:54:35] Starting 'css:project'...
[11:54:35] Starting 'browser-sync'...
[11:54:35] Finished 'watch' after 11 ms
[11:54:36] 'styleguide' errored after 787 ms
[11:54:36] SyntaxError: Unexpected token  
    at Object.parse (native)
    at Object.loadFiles (C:\Users\pb00230\Projects\GitHub\component-library-core\lib\compolib.components.js:146:29)
    at Object.module.exports.renderOne (C:\Users\pb00230\Projects\GitHub\component-library-core\lib\compolib.components.js:29:22)
    at Object.renderAll (C:\Users\pb00230\Projects\GitHub\component-library-core\lib\compolib.components.js:104:14)
    at build (C:\Users\pb00230\Projects\GitHub\component-library-core\lib\compolib.build.js:24:14)
    at CompoLib (C:\Users\pb00230\Projects\GitHub\component-library-core\index.js:19:3)
    at c:\Users\pb00230\Erizone\si-design\_front-end\gulpfile.js:97:3
    at taskWrapper (c:\Users\pb00230\Erizone\si-design\_front-end\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
[11:54:36] 'default' errored after 788 ms
[11:54:36] The following tasks did not complete: css:project, browser-sync
[11:54:36] Did you forget to signal async completion?
```

**Comment by b1zzu** [comment]
Fix with this Pull request https://github.com/karlisup/component-library-core/pull/3
